name: Run Tests

on: [push, pull_request]

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
          submodules: true

    - name: Install PHPUnit
      run: wget https://phar.phpunit.de/phpunit-9.5.24.phar

    - name: Run Tests
      run: phpdbg -qrr phpunit-9.5.24.phar tests --configuration tests/phpunit.xml